---
name: code-quality
on:
  push:
    branches: [main]
  pull_request_target:
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Spell Check
        # https://github.com/crate-ci/typos
        uses: crate-ci/typos@0f0ccba9ed1df83948f0c15026e4f5ccfce46109
      - name: Shell and shfmt Check
        # https://github.com/luizm/action-sh-checker
        uses: luizm/action-sh-checker@17bd25a6ee188d2b91f677060038f4ba37ba14b2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: --simplify --indent 4 --case-indent
        with:
          sh_checker_comment: true
